version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tkrlabo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tkrlabo
      MYSQL_USER: tkrlabo
      MYSQL_PASSWORD: tkrlabo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.d:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: